services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: coffee_timer
      POSTGRES_PASSWORD: coffee_timer_dev
      POSTGRES_DB: coffee_timer
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
